#!/bin/bash
#
# helper for typing into the phone, and optionally
# - clear the existing text first
# - hit return
#

function del() {
 keys=""
 count=0
 while [ $count -lt 32 ]; do   
   keys="67 $keys"
   ((count++))
 done
 adb shell input keyevent $keys
}

function enter() {
 adb shell input keyevent 66
}


case "$1" in
"-c") 
  shift
  del
  adb shell input text "$@"
;;
"-cr"|"-rc") 
  shift
  del
  adb shell input text "$@"
  enter
;;
"-r") 
  enter
;;
"") 
 echo "Usage: $0 [-r|-c|-cr|-rc] text ..."
;;
*)
  adb shell input text "$@"
;;
esac

