#!/bin/bash

echo "are you sure? will pull apk from phone, and create files"
read

adb shell pm list packages -f apn
adb shell pm list packages -f com.verizon.familybase.companion

adb pull /system/priv-app/vzwapnpermission/vzwapnpermission.apk vzwapnpermission.apk 
adb pull /system/priv-app/VZWAPNService/VZWAPNService.apk VZWAPNService.apk

adb pull  /data/app/com.verizon.familybase.companion-1/base.apk companion_app.apk

adb shell pm dump com.verizon.familybase.companion >pkgdump.txt

grep -i permission pkgdump.txt

jarsigner -verify -verbose -certs vzwapnpermission.apk >vzwapnpermission.sigs
jarsigner -verify -verbose -certs VZWAPNService.apk > VZWAPNService.sigs
jarsigner -verify -verbose -certs companion_app.apk > companion_app.sigs

head -n 20 *.sigs

aapt dump xmltree companion_app.apk AndroidManifest.xml >companion_app.manifest

grep VZWAPPAPN companion_app.manifest


