#!/usr/sww/bin/bash
# need explicit path to bash on Sol/SunOS: merc/now/argus

cd
#. .bashrc
PATH=$PATH:/usr/sww/bin

cd $HOME/public_html/Mail
cp $HOME/Mail/in /tmp/fullmailcopy
cat /var/mail/$LOGNAME >> /tmp/fullmailcopy

frm /tmp/fullmailcopy | grep -n . \
        | sed 's/^\(.\):/<a href="\1">\1<\/a>: /' \
        | sed 's/^\(..\):/<a href="\1">\1<\/a>: /' \
        | sed 's/^\(...\):/<a href="\1">\1<\/a>: /' \
        | sed 's/^\(....\):/<a href="\1">\1<\/a>: /' \
	> index
cat index | sed 's/$/<br>/'  > index.html
frm /tmp/fullmailcopy | grep -n . > index

/bin/rm [0-9] [0-9][0-9] [0-9][0-9][0-9] 2>/dev/null

numlines=`frm /tmp/fullmailcopy |wc -l|awk '{print $1}'`
maxlines=$numlines
while [ $numlines -gt 0 ]
do
	readmsg -f /tmp/fullmailcopy $numlines > $numlines
	let numlines=$numlines-1
done
/bin/rm -f /tmp/fullmailcopy
