#!/usr/bin/perl

print "HTTP/1.1 200 OK\r\n";
print "Content-Type: video/mpeg\r\n";
print "Transfer-Encoding: chunked\r\n";
print "\r\n";

my $r = 1;
while ($r) {
      
    my $var;
    $r = read STDIN, $var, 256;
    
    if ($r < 0) {
	$r = 0;
    }  
    
    printf "%x\r\n", $r;
    
    print $var;
    
}
