#!/bin/bash
#
# from the GET:
#lynx -dump "http://www3.igl.net:81/perl/find.cgi" | g "[0-9]\.[0-9]"
# expected output format (idle is row 2):
#
###                               70.103%
###                                 1.9
###                                112.1
###                                61.9%

prnt=0
case $1 in
"-p") prnt=1 ;;
esac

#players="ren-n-stimpy tdh"
players="ren-n-stimpy"

for i in $players
do 

	#path=soc&ser=943&template=myleague&genre=strategy
	idlet=`lynx -dump \
	   "http://www3.igl.net:81/perl/find.cgi?path=soc&svr=cgi3&name=$i" \
		| egrep "[0-9]\.[0-9]" | paste  - - - - | awk '{print $2}'`

	# echo "idle time = $idlet"

	idlet=`echo $idlet | cut -d"." -f1`

	[ $prnt -eq 1 ] && echo "$i idle days: $idlet"

	if [ $idlet -gt 14 ]
	then
		echo "$i idle days: $idlet" \
			| mail -s "SoC idle time: $i" hodes@cs.berkeley.edu
	fi

done
