#!/bin/sh

#set -o xtrace

rlcmd="telnet -ax"

# provide monitoring
echo "`date` : $rlcmd $1" >> ~/var/rlogin-results

case $2 in
"") xterm -sb -sl 1200 -title $1 -sb -bg `getColor` -e $rlcmd $1 ; exit ;;
esac

xterm -sb -sl 1200 -title $1 -sb -bg `getColor` -e $rlcmd -l $2 $1


