#!/bin/sh

# $Id: sortuud,v 1.8 91/11/14 17:47:57 maman Exp Locker: maman $

: ${UUDCOMMAND:=myuud} ${UUDOPTIONS:="-v -c"}
: ${UUDSUPPRESS:="xx14217yy bidon"} ${UUDKEEP:="."}
: ${RXLOG:="${HOME}/.rx.log"}

b0=`basename ${0}`

Usage="\
Usage: ${b0} [-v] [-l] [-s n] file ...
Description: Tries to sort articles by subject line and give them in
	     order to '${UUDCOMMAND} ${UUDOPTIONS}'.  Each file
	     contains only one article.
Options: -v : verbose output
	 -l : prints only filenames in order
	 -s : generates the list starting from n and containing the
	      same figure count.  It can appear more than once.
Variables: exported UUDCOMMAND and UUDOPTIONS used to change uudecode
	   program and options.
Bugs: Sometimes fooled.
"

verbose=off
liste=
while [ $# -gt 0 ]
do
    case "${1}" in
	-[Hh]*) echo>&2 -n "${Usage}"; exit 1;;
	-x) set -x;;
	-v) verbose=on;;
	-l) verbose=list;;
	-s) liste="${liste}
${2}"
	    suff=
	    pref="${2}"
	    while
		num=`expr "${pref}" : '.*\([0-9]\)$' + 1 2>/dev/null`
	    do
		pref=`expr "${pref}" : '\(.*\)[0-9]$'`
		if [ "${num}" -lt 10 ]
		then liste="${liste}
${pref}[${num}-9]${suff}"
		fi
		suff="${suff}[0-9]"
	    done
	    shift;;
	*) liste="${liste}
${1}";;
    esac
    shift
done

[ -z "${liste}" ] && { echo>&2 -n "${Usage}"; exit 1; }

LISTE=`
    grep '^Subject: ' ${liste} /dev/null /dev/null |
    sed -e '
	s/[:	]/ /g
	s/[.][Gg][Ii][Ff] / /g
	s/[Pp][Aa][Rr][Tt]\([0-9]\)/part \1/g
	s/  *[Pp][Aa][Rr][Tt] *\([0-9]*\) *[of\/]* *\([0-9]*\)/:\2: \1:/
	s/ *[[(] *[Pp][Aa][Rr][Tt] *\([0-9]*\) *\/ *\([0-9]*\) *[])]/:\2: \1:/
	s/ *[[(] *\([0-9][0-9]*\) *[of\/]* *\([0-9][0-9]*\) *[])]/:\2: \1:/
	s/\([ (]\)\([0-9][0-9]*\)/\1 00000\2/g
	s/ 0*\([0-9][0-9][0-9]\)/ \1/g
	s/ * /_/g
	s/_/ /
	s/_*_Re_*_/_/g
	s/_*[(_]_*[Rr][Ee][Pp][Oo][Ss][Tt]_*_[Oo][Ff]_*[)_]_*/_/g
	s/_*[(_]_*[Rr][Ee][Pp][Oo][Ss][Tt]_*[)_]_*/_/g
	s/[[{(]females[]})]/{female}/g
	s/^\([^ ]* \)_*Subject_*_/\1/
	s/ * / /g
	s/_//g
	s/\[\([0-9]*\/[0-9]*\)/[00000\1/
	s/\[0*\([0-9][0-9][0-9][0-9][0-9]\/[0-9]*\)/[00000\1/
	' |
    egrep -v "${UUDSUPPRESS}" |
    egrep "${UUDKEEP}" |
    tee -a "${RXLOG}" |
    sort +1 -f -u -b -i |
    sed -e 's/ .*$//'
`

[ -z "${LISTE}" ] && {
    echo>&2 "No files."
    exit 1
}

echo "${LISTE}" > .sortuud.lis

case "${verbose}" in
    "on") grep '^Subject: ' ${LISTE};;
    "list") echo ${LISTE}; exit;;
esac |
tee -a "${RXLOG}"

(
    cat ${LISTE} |
    sed -e 's/CUT HERE-----/cut HERE-----/' |
    ${UUDCOMMAND} ${UUDOPTIONS} -
) |
tee -a "${RXLOG}"
